#!/bin/sh
#
## Don't edit this file
## Edit user configuation in /etc/default/harpoon to change
##
## Make sure init script is executable
## sudo chmod +x /opt/harpoon/init.ubuntu
##
## Install the init script
## sudo ln -s /opt/harpoon/init.ubuntu /etc/init.d/harpoon
##
## Create the harpoon daemon user:
## sudo adduser --system --no-create-home harpoon
##
## Make sure /opt/harpoon is owned by the harpoon user
## sudo chown harpoon:nogroup -R /opt/harpoon
##
## Touch the default file to stop the warning message when starting
## sudo touch /etc/default/harpoon
##
## To start harpoon automatically
## sudo  update-rc.d harpoon defaults
##
## To start/stop/restart harpoon
## sudo service harpoon start
## sudo service harpoon stop
## sudo service harpoon restart
##
## HARPOON_USER=         #$RUN_AS, username to run harpoon under, the default is harpoon
## HARPOON_HOME=         #$APP_PATH, the location of harpoon.py, the default is /opt/harpoon
## HARPOON_PIDFILE=      #$PID_FILE, the location of harpoon.pid, the default is /var/run/harpoon/harpoon.pid
## PYTHON_BIN=           #$DAEMON, the location of the python binary, the default is /usr/bin/python
## HARPOON_OPTS=         #$EXTRA_DAEMON_OPTS, extra cli option for harpoon, i.e. " --config=/opt/harpoon/config.ini"
## SSD_OPTS=             #$EXTRA_SSD_OPTS, extra start-stop-daemon option like " --group=users"
##
## EXAMPLE if want to run as different user
## add HARPOON_USER=username to /etc/default/harpoon
## otherwise default harpoon is used
#
### BEGIN INIT INFO
# Provides:          harpoon
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of harpoon
# Description:       starts instance of harpoon using start-stop-daemon
### END INIT INFO

# Script name
NAME=harpoon

# App name
DESC=harpoon

SETTINGS_LOADED=FALSE

. /lib/lsb/init-functions

# Source harpoon configuration
if [ -f /etc/default/harpoon ]; then
    SETTINGS=/etc/default/harpoon
else
    log_warning_msg "/etc/default/harpoon not found using default settings.";
fi

check_retval() {
    if [ $? -eq 0 ]; then
        log_end_msg 0
        return 0
    else
        log_end_msg 1
        exit 1
    fi
}

load_settings() {
    if [ $SETTINGS_LOADED != "TRUE" ]; then
        . $SETTINGS

        ## The defaults
        # Run as username
        RUN_AS=${HARPOON_USER-harpoon}

        # Path to app HARPOON_HOME=path_to_app_harpoon.py
        APP_PATH=${HARPOON_HOME-/opt/harpoon}

        # Path to store PID file
        PID_FILE=${HARPOON_PIDFILE-/var/run/harpoon/harpoon.pid}

        # Path to python bin
        DAEMON=${PYTHON_BIN-/usr/bin/python}

        # Extra daemon option like: HARPOON_OPTS=" --config=/opt/harpoon/conf/harpoon.conf"
        EXTRA_DAEMON_OPTS=${HARPOON_OPTS-}

        # Extra start-stop-daemon option like START_OPTS=" --group=users"
        EXTRA_SSD_OPTS=${SSD_OPTS-}

        DAEMON_OPTS=" harpoon.py -d -p ${PID_FILE}"

        SETTINGS_LOADED=TRUE
    fi

    [ -x $DAEMON ] || {
        log_warning_msg "$DESC: Can't execute daemon, aborting. See $DAEMON";
        return 1;}

    return 0
}

load_settings || exit 0

is_running () {
    # returns 1 when running, else 0.
    if [ -e $PID_FILE ]; then
      PID=`cat $PID_FILE`

      RET=$?
      [ $RET -gt 1 ] && exit 1 || return $RET
    else
      return 1
    fi
}

handle_pid () {
    PID_PATH=`dirname $PID_FILE`
    [ -d $PID_PATH ] || mkdir -p $PID_PATH && chown -R $RUN_AS $PID_PATH > /dev/null || {
        log_warning_msg "$DESC: Could not create $PID_FILE, See $SETTINGS, aborting.";
        return 1;}

    if [ -e $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if ! kill -0 $PID > /dev/null 2>&1; then
            log_warning_msg "Removing stale $PID_FILE"
            rm $PID_FILE
        fi
    fi
}

handle_updates () {
    chown -R $RUN_AS $APP_PATH > /dev/null || {
        log_warning_msg "$DESC: $APP_PATH not writable by $RUN_AS for web-updates";
        return 0; }
}

start_harpoon () {
    handle_pid
    handle_updates
    if ! is_running; then
        log_daemon_msg "Starting $DESC"
        start-stop-daemon -o -d $APP_PATH -c $RUN_AS --start $EXTRA_SSD_OPTS --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        check_retval
    else
        log_success_msg "$DESC: already running (pid $PID)"
    fi
}

stop_harpoon () {
    if is_running; then
        log_daemon_msg "Stopping $DESC"
        start-stop-daemon -o --stop --pidfile $PID_FILE --retry 15
        check_retval
    else
        log_success_msg "$DESC: not running"
    fi
}

case "$1" in
    start)
        start_harpoon
        ;;
    stop)
        stop_harpoon
        ;;
    restart|force-reload)
        stop_harpoon
        start_harpoon
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$DAEMON" "$DESC"
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
